#!/usr/bin/env bash
# Install the local git hooks. Run once per clone:
#
#   bash .github/scripts/install-hooks.sh
#
# Hooks are not versioned by git itself, so this script is the versioned part
# and .git/hooks holds the generated copies. Re-run it after pulling changes
# here; it overwrites unconditionally.
#
# # What these guard, and why a .gitignore entry is not enough
#
# .gitignore is a name blocklist. It stops the files it happens to name, and
# every new coding tool ships a new name. It is also trivially defeated by
# `git add -f`, which is exactly the flag someone reaches for at 2am when a
# file "should obviously be committed".
#
# The exposure this protects is real and specific: the agent scratch directory
# in this repo has held a private-range IP, a host filesystem path, an SSH test
# keypair reference, and the branch structure of a separate private project.
# None of it has ever been committed. But this is a PUBLIC repository, and a
# public push is not revocable — the Go module proxy and GitHub's fork network
# both retain content independently of anything you delete afterwards. The
# whole point is that the recovery story is bad enough to justify prevention.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
hooks=$(git rev-parse --git-path hooks)
mkdir -p "$hooks"

# --- pre-commit: refuse to stage agent scratch or credential-shaped paths ----
cat >"$hooks/pre-commit" <<'HOOK'
#!/bin/sh
# Generated by .github/scripts/install-hooks.sh — edit there, not here.
staged=$(git diff --cached --name-only --diff-filter=ACMR)
[ -n "$staged" ] || exit 0

blocked=$(printf '%s\n' "$staged" | grep -nE \
  '(^|/)\.(claude|codex|continue|cursor|opencode)/|(^|/)\.mcp\.json$|(^|/)(CLAUDE|AGENT|AGENTS|GEMINI)\.md$|(^|/)\.(cursorrules|clinerules|windsurfrules|roomodes)$|(^|/)\.env($|\.)|(^|/)(id_rsa|id_ecdsa|id_ed25519)|\.(pem|key|p12|pfx)$|(^|/)(credentials|kubeconfig|\.netrc)$' \
  || true)

if [ -n "$blocked" ]; then
  echo "pre-commit: refusing to stage agent-tooling or credential paths:" >&2
  printf '%s\n' "$blocked" | sed 's/^/  /' >&2
  echo >&2
  echo "This repository is PUBLIC and a push cannot be taken back." >&2
  echo "If this is genuinely intended, bypass deliberately:  git commit --no-verify" >&2
  exit 1
fi
exit 0
HOOK

# --- commit-msg: keep AI attribution trailers out of the public history -----
# Not a secrecy measure; the maintainer is open about using assistance. It is
# consistency: three stray trailers across forty commits with no mention in any
# document reads as tooling leakage rather than a position, and on a security
# library the inference a reader draws from that is the unkind one.
cat >"$hooks/commit-msg" <<'HOOK'
#!/bin/sh
# Generated by .github/scripts/install-hooks.sh — edit there, not here.
if grep -qiE '^(Co-authored-by:.*(claude|anthropic|copilot|cursor))|Generated with \[?(Claude|Cursor)' "$1"; then
  echo "commit-msg: AI attribution trailer blocked (see .github/scripts/install-hooks.sh)" >&2
  echo "  strip the trailer, or bypass with: git commit --no-verify" >&2
  exit 1
fi
exit 0
HOOK

chmod +x "$hooks/pre-commit" "$hooks/commit-msg"

echo "installed:"
echo "  $hooks/pre-commit   — blocks agent-tooling and credential paths"
echo "  $hooks/commit-msg   — blocks AI attribution trailers"
echo
echo "Both are bypassable with --no-verify, deliberately: a hook that cannot be"
echo "overridden gets deleted the first time it is wrong. The point is to make"
echo "the mistake require a decision."
