#!/usr/bin/env bash
# Install the local git hooks. Run once per clone:
#
#   bash .github/scripts/install-hooks.sh
#
# Hooks are not versioned by git itself, so this script is the versioned part
# and .git/hooks holds the generated copies. Re-run it after pulling changes
# here; it overwrites unconditionally.
#
# # What these guard, and why a .gitignore entry is not enough
#
# .gitignore is a name blocklist. It stops the files it happens to name, and
# every new coding tool ships a new name. It is also trivially defeated by
# `git add -f`, which is exactly the flag someone reaches for at 2am when a
# file "should obviously be committed".
#
# The exposure this protects is real and specific: the agent scratch directory
# in this repo has held a private-range IP, a host filesystem path, an SSH test
# keypair reference, and the branch structure of a separate private project.
# None of it has ever been committed. But this is a PUBLIC repository, and a
# public push is not revocable — the Go module proxy and GitHub's fork network
# both retain content independently of anything you delete afterwards. The
# whole point is that the recovery story is bad enough to justify prevention.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
hooks=$(git rev-parse --git-path hooks)
mkdir -p "$hooks"

# --- pre-commit: refuse to stage agent scratch or credential-shaped paths ----
cat >"$hooks/pre-commit" <<'HOOK'
#!/bin/sh
# Generated by .github/scripts/install-hooks.sh — edit there, not here.
staged=$(git diff --cached --name-only --diff-filter=ACMR)
[ -n "$staged" ] || exit 0

blocked=$(printf '%s\n' "$staged" | grep -nE \
  '(^|/)\.(claude|codex|continue|cursor|opencode)/|(^|/)\.mcp\.json$|(^|/)(CLAUDE|AGENT|AGENTS|GEMINI)\.md$|(^|/)\.(cursorrules|clinerules|windsurfrules|roomodes)$|(^|/)\.env($|\.)|(^|/)(id_rsa|id_ecdsa|id_ed25519)|\.(pem|key|p12|pfx)$|(^|/)(credentials|kubeconfig|\.netrc)$' \
  || true)

if [ -n "$blocked" ]; then
  echo "pre-commit: refusing to stage agent-tooling or credential paths:" >&2
  printf '%s\n' "$blocked" | sed 's/^/  /' >&2
  echo >&2
  echo "This repository is PUBLIC and a push cannot be taken back." >&2
  echo "If this is genuinely intended, bypass deliberately:  git commit --no-verify" >&2
  exit 1
fi

# Secrets in what is staged. Fast (it reads only the staged diff), and this is
# the cheapest place to catch one: before it is in a commit at all. A scanner
# that is not installed is reported, not skipped silently; pre-push refuses.
if command -v gitleaks >/dev/null 2>&1; then
  if ! gitleaks protect --staged --redact --no-banner --log-level=warn >&2; then
    echo "pre-commit: gitleaks flagged the staged changes (a false positive is fixed by" >&2
    echo "  rewording the line, not by a later commit: CI scans every commit)." >&2
    exit 1
  fi
else
  echo "pre-commit: gitleaks not installed; staged changes were not scanned" >&2
fi

# gofmt on the staged content of each staged Go file (not the working copy).
if command -v gofmt >/dev/null 2>&1; then
  bad=
  for f in $(printf '%s\n' "$staged" | grep -E '\.go$' | grep -v '/testdata/'); do
    [ -n "$(git show ":$f" | gofmt -l 2>/dev/null)" ] && bad="$bad $f"
  done
  if [ -n "$bad" ]; then
    echo "pre-commit: not gofmt-clean:$bad" >&2
    exit 1
  fi
fi
exit 0
HOOK

# --- pre-push: check exactly the commits this push would publish -------------
# The checks live in check-commits.sh so they can be run by hand on any range.
# They read commits, not the working tree, so pushing a branch that is not
# checked out is checked correctly. The hook runs an installed COPY of the
# script, not the one in the working tree: hooks are shared by every worktree,
# and a worktree on an older branch may not have the file at all.
cp .github/scripts/check-commits.sh "$hooks/check-commits.sh"
cat >"$hooks/pre-push" <<'HOOK'
#!/bin/sh
# Generated by .github/scripts/install-hooks.sh — edit there, not here.
checks=$(git rev-parse --git-path hooks)/check-commits.sh
zero=0000000000000000000000000000000000000000
status=0
while read -r _ref sha _rref rsha; do
  [ "$sha" = "$zero" ] && continue # deleting a remote branch
  if [ "$rsha" = "$zero" ]; then
    # New branch: everything not already on the remote's default branch.
    base=$(git merge-base "$sha" refs/remotes/origin/main 2>/dev/null) || base=
    [ -n "$base" ] || continue
    range="$base..$sha"
  else
    range="$rsha..$sha"
  fi
  bash "$checks" "$range" || status=1
done
if [ "$status" -ne 0 ]; then
  echo "pre-push: refused. A push to a public repository cannot be taken back." >&2
  echo "  bypass deliberately with: git push --no-verify" >&2
fi
exit $status
HOOK

# --- commit-msg: keep AI attribution trailers out of the public history -----
# Not a secrecy measure; the maintainer is open about using assistance. It is
# consistency: three stray trailers across forty commits with no mention in any
# document reads as tooling leakage rather than a position, and on a security
# library the inference a reader draws from that is the unkind one.
cat >"$hooks/commit-msg" <<'HOOK'
#!/bin/sh
# Generated by .github/scripts/install-hooks.sh — edit there, not here.
if grep -qiE '^(Co-authored-by:.*(claude|anthropic|copilot|cursor))|Generated with \[?(Claude|Cursor)' "$1"; then
  echo "commit-msg: AI attribution trailer blocked (see .github/scripts/install-hooks.sh)" >&2
  echo "  strip the trailer, or bypass with: git commit --no-verify" >&2
  exit 1
fi
exit 0
HOOK

chmod +x "$hooks/pre-commit" "$hooks/commit-msg" "$hooks/pre-push"

echo "installed:"
echo "  $hooks/pre-commit   — blocks agent-tooling and credential paths, secrets and unformatted Go in the staged changes"
echo "  $hooks/commit-msg   — blocks AI attribution trailers"
echo "  $hooks/pre-push     — re-checks every commit being pushed: paths, secrets, trailers, signatures, gofmt"
command -v gitleaks >/dev/null 2>&1 || echo "  NOTE: gitleaks is not installed; pre-push will refuse until it is (go install github.com/zricethezav/gitleaks/v8@latest)"
echo
echo "All are bypassable with --no-verify, deliberately: a hook that cannot be"
echo "overridden gets deleted the first time it is wrong. The point is to make"
echo "the mistake require a decision."
