// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// The golden vectors and the bcryptHash vector are upstream's
// (ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf_test.go at v0.56.0); the tests
// around them are secmem-crypto's.

package bcryptpbkdf

import (
	"bytes"
	"errors"
	"testing"
)

// Test vectors generated by the reference implementation from OpenBSD.
var golden = []struct {
	rounds                 int
	password, salt, result []byte
}{
	{
		12,
		[]byte("password"),
		[]byte("salt"),
		[]byte{
			0x1a, 0xe4, 0x2c, 0x05, 0xd4, 0x87, 0xbc, 0x02, 0xf6,
			0x49, 0x21, 0xa4, 0xeb, 0xe4, 0xea, 0x93, 0xbc, 0xac,
			0xfe, 0x13, 0x5f, 0xda, 0x99, 0x97, 0x4c, 0x06, 0xb7,
			0xb0, 0x1f, 0xae, 0x14, 0x9a,
		},
	},
	{
		3,
		[]byte("passwordy\x00PASSWORD\x00"),
		[]byte("salty\x00SALT\x00"),
		[]byte{
			0x7f, 0x31, 0x0b, 0xd3, 0xe7, 0x8c, 0x32, 0x80, 0xc5,
			0x9c, 0xe4, 0x59, 0x52, 0x11, 0xa2, 0x92, 0x8e, 0x8d,
			0x4e, 0xc7, 0x44, 0xc1, 0xed, 0x2e, 0xfc, 0x9f, 0x76,
			0x4e, 0x33, 0x88, 0xe0, 0xad,
		},
	},
	{
		// See http://thread.gmane.org/gmane.os.openbsd.bugs/20542
		8,
		[]byte("секретное слово"),
		[]byte("посолить немножко"),
		[]byte{
			0x8d, 0xf4, 0x3f, 0xc6, 0xfe, 0x13, 0x1f, 0xc4, 0x7f,
			0x0c, 0x9e, 0x39, 0x22, 0x4b, 0xd9, 0x4c, 0x70, 0xb6,
			0xfc, 0xc8, 0xee, 0x81, 0x35, 0xfa, 0xdd, 0xf6, 0x11,
			0x56, 0xe6, 0xcb, 0x27, 0x33, 0xea, 0x76, 0x5f, 0x31,
			0x5a, 0x3e, 0x1e, 0x4a, 0xfc, 0x35, 0xbf, 0x86, 0x87,
			0xd1, 0x89, 0x25, 0x4c, 0x1e, 0x05, 0xa6, 0xfe, 0x80,
			0xc0, 0x61, 0x7f, 0x91, 0x83, 0xd6, 0x72, 0x60, 0xd6,
			0xa1, 0x15, 0xc6, 0xc9, 0x4e, 0x36, 0x03, 0xe2, 0x30,
			0x3f, 0xbb, 0x43, 0xa7, 0x6a, 0x64, 0x52, 0x3f, 0xfd,
			0xa6, 0x86, 0xb1, 0xd4, 0x51, 0x85, 0x43,
		},
	},
}

func TestDerive_Golden(t *testing.T) {
	for i, v := range golden {
		ws := NewWorkspace()
		got := make([]byte, len(v.result))
		if err := Derive(got, v.password, v.salt, v.rounds, ws); err != nil {
			t.Errorf("%d: %v", i, err)
			continue
		}
		ws.Wipe()
		if !bytes.Equal(got, v.result) {
			t.Errorf("%d: expected\n%x\n, got\n%x\n", i, v.result, got)
		}
	}
}

// TestDerive_BoundWorkspace runs the vectors through a Workspace overlaid on
// a caller's region (the SecureBuffer path in secmem-crypto) and requires a
// reused Workspace to give the same answer as a fresh one.
func TestDerive_BoundWorkspace(t *testing.T) {
	region := make([]byte, Size+64)
	off := 0
	for uintptrOf(region[off:])%8 != 0 {
		off++
	}
	ws := Bind(region[off:])
	for i, v := range golden {
		for rep := 0; rep < 2; rep++ {
			got := make([]byte, len(v.result))
			if err := Derive(got, v.password, v.salt, v.rounds, ws); err != nil {
				t.Fatalf("%d: %v", i, err)
			}
			if !bytes.Equal(got, v.result) {
				t.Errorf("%d rep %d: bound workspace: expected %x, got %x", i, rep, v.result, got)
			}
		}
	}
	ws.Wipe()
	if !isZero(region) {
		t.Error("the bound region holds residue after Wipe")
	}
}

// TestDerive_SaltSpill pins that the heap spill for a salt longer than the
// reserve derives the same key as the reserve path, and that Derive wiped
// the spill buffer. The reserve path is driven directly so the comparison is
// the same code with two buffers, not two vectors.
func TestDerive_SaltSpill(t *testing.T) {
	salt := bytes.Repeat([]byte("s"), saltReserve+7)
	password := []byte("password")

	ws := NewWorkspace()
	want := make([]byte, 40)
	big := make([]byte, len(salt)+4)
	derive(want, password, salt, 4, ws, big)

	got := make([]byte, 40)
	if err := Derive(got, password, salt, 4, ws); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("spill path derived %x, direct path %x", got, want)
	}
	if isZero(got) {
		t.Fatal("control failed: derived key is all zero")
	}

	// The spill buffer is wiped by Derive; the reserve, which the spill
	// path never uses, must not have been written either.
	if !isZero(ws.saltIn[:]) {
		t.Error("the reserve was written on the spill path")
	}
	ws.Wipe()
}

// TestDerive_Bounds pins the input rules, which are upstream's, plus the
// empty output this API can express and upstream's could not.
func TestDerive_Bounds(t *testing.T) {
	ws := NewWorkspace()
	out := make([]byte, 32)
	cases := []struct {
		name          string
		out           []byte
		password      []byte
		salt          []byte
		rounds        int
		want          error
		wantWorkspace bool
	}{
		{"zero rounds", out, []byte("p"), []byte("s"), 0, ErrRounds, false},
		{"empty password", out, nil, []byte("s"), 1, ErrPassword, false},
		{"empty salt", out, []byte("p"), nil, 1, ErrSalt, false},
		{"salt too long", out, []byte("p"), make([]byte, 1<<20+1), 1, ErrSalt, false},
		{"salt at bound", out, []byte("p"), make([]byte, 1<<20), 1, nil, true},
		{"empty output", nil, []byte("p"), []byte("s"), 1, ErrOutput, false},
		{"output too long", make([]byte, 1025), []byte("p"), []byte("s"), 1, ErrKeyLen, false},
		{"output at bound", make([]byte, 1024), []byte("p"), []byte("s"), 1, nil, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ws.Wipe()
			err := Derive(tc.out, tc.password, tc.salt, tc.rounds, ws)
			if !errors.Is(err, tc.want) {
				t.Fatalf("got %v, want %v", err, tc.want)
			}
			if written := !isZero(ws.shapass[:]); written != tc.wantWorkspace {
				t.Fatalf("workspace written = %v, want %v (a rejected input must not start deriving)", written, tc.wantWorkspace)
			}
		})
	}
	ws.Wipe()
}

func TestBcryptHash(t *testing.T) {
	good := []byte{
		0x87, 0x90, 0x48, 0x70, 0xee, 0xf9, 0xde, 0xdd, 0xf8, 0xe7,
		0x61, 0x1a, 0x14, 0x01, 0x06, 0xe6, 0xaa, 0xf1, 0xa3, 0x63,
		0xd9, 0xa2, 0xc5, 0x04, 0xdb, 0x35, 0x64, 0x43, 0x72, 0x1e,
		0xb5, 0x55,
	}
	var pass, salt [64]byte
	var result [32]byte
	for i := 0; i < 64; i++ {
		pass[i] = byte(i)
		salt[i] = byte(i + 64)
	}
	var c Cipher
	bcryptHash(&result, pass[:], salt[:], &c)
	if !bytes.Equal(result[:], good) {
		t.Errorf("expected %x, got %x", good, result)
	}
	// Re-keying in place must give the same answer from a dirty Cipher.
	bcryptHash(&result, pass[:], salt[:], &c)
	if !bytes.Equal(result[:], good) {
		t.Errorf("second hash from the same Cipher: expected %x, got %x", good, result)
	}
}

func TestBind_Refusals(t *testing.T) {
	mustPanic := func(name string, f func()) {
		t.Helper()
		defer func() {
			if recover() == nil {
				t.Errorf("%s: no panic", name)
			}
		}()
		f()
	}
	mustPanic("short region", func() { Bind(make([]byte, Size-1)) })
	region := make([]byte, Size+8)
	off := 1
	if uintptrOf(region[off:])%8 == 0 {
		off++
	}
	mustPanic("misaligned region", func() { Bind(region[off:]) })
	mustPanic("nil workspace", func() { _ = Derive(make([]byte, 1), []byte("p"), []byte("s"), 1, nil) })
}
