package secmemcrypto

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"strings"
	"testing"

	"github.com/deadpoets/secmem"
)

// bcryptGolden holds test vectors generated by the reference implementation
// from OpenBSD, as carried by golang.org/x/crypto/ssh/internal/bcrypt_pbkdf.
// internal/bcryptpbkdf pins the fork against them directly; these run the
// same vectors through the exported wrapper, which is what fixes the
// argument order and the rule that out.Len() is the key length.
var bcryptGolden = []struct {
	name                   string
	rounds                 int
	password, salt, result []byte
}{
	{
		"password/salt/12", 12,
		[]byte("password"), []byte("salt"),
		[]byte{
			0x1a, 0xe4, 0x2c, 0x05, 0xd4, 0x87, 0xbc, 0x02, 0xf6,
			0x49, 0x21, 0xa4, 0xeb, 0xe4, 0xea, 0x93, 0xbc, 0xac,
			0xfe, 0x13, 0x5f, 0xda, 0x99, 0x97, 0x4c, 0x06, 0xb7,
			0xb0, 0x1f, 0xae, 0x14, 0x9a,
		},
	},
	{
		"embedded NULs/3", 3,
		[]byte("passwordy\x00PASSWORD\x00"), []byte("salty\x00SALT\x00"),
		[]byte{
			0x7f, 0x31, 0x0b, 0xd3, 0xe7, 0x8c, 0x32, 0x80, 0xc5,
			0x9c, 0xe4, 0x59, 0x52, 0x11, 0xa2, 0x92, 0x8e, 0x8d,
			0x4e, 0xc7, 0x44, 0xc1, 0xed, 0x2e, 0xfc, 0x9f, 0x76,
			0x4e, 0x33, 0x88, 0xe0, 0xad,
		},
	},
	{
		// An 87-byte output: more than one bcrypt block, so the
		// interleave the fork reproduces without an intermediate buffer
		// is exercised through the public entry point too.
		"non-ASCII/8", 8,
		[]byte("секретное слово"), []byte("посолить немножко"),
		[]byte{
			0x8d, 0xf4, 0x3f, 0xc6, 0xfe, 0x13, 0x1f, 0xc4, 0x7f,
			0x0c, 0x9e, 0x39, 0x22, 0x4b, 0xd9, 0x4c, 0x70, 0xb6,
			0xfc, 0xc8, 0xee, 0x81, 0x35, 0xfa, 0xdd, 0xf6, 0x11,
			0x56, 0xe6, 0xcb, 0x27, 0x33, 0xea, 0x76, 0x5f, 0x31,
			0x5a, 0x3e, 0x1e, 0x4a, 0xfc, 0x35, 0xbf, 0x86, 0x87,
			0xd1, 0x89, 0x25, 0x4c, 0x1e, 0x05, 0xa6, 0xfe, 0x80,
			0xc0, 0x61, 0x7f, 0x91, 0x83, 0xd6, 0x72, 0x60, 0xd6,
			0xa1, 0x15, 0xc6, 0xc9, 0x4e, 0x36, 0x03, 0xe2, 0x30,
			0x3f, 0xbb, 0x43, 0xa7, 0x6a, 0x64, 0x52, 0x3f, 0xfd,
			0xa6, 0x86, 0xb1, 0xd4, 0x51, 0x85, 0x43,
		},
	},
}

func TestBcryptPBKDFInto_Golden(t *testing.T) {
	for _, g := range bcryptGolden {
		t.Run(g.name, func(t *testing.T) {
			out := newTestBuffer(t, len(g.result))
			if err := BcryptPBKDFInto(g.password, g.salt, g.rounds, out); err != nil {
				t.Fatal(err)
			}
			if got := bufferBytes(t, out); !bytes.Equal(got, g.result) {
				t.Errorf("derived\n got %x\nwant %x", got, g.result)
			}
		})
	}
}

// TestBcryptPBKDFInto_ReproducesSSHKeygenKeyAndIV is the interoperability
// proof, and the one that does not share a source with the vectors above.
// It takes a file a real ssh-keygen wrote, reads the salt and rounds it
// recorded, derives the 48-byte key and IV through the exported function,
// and decrypts the file's private block with the standard library alone.
// The format's own check integers — two random words ssh-keygen wrote twice
// before encrypting — must come back equal, which they can only do if this
// function reproduced ssh-keygen's derivation byte for byte. It is written
// against the stdlib rather than this package's cipher helpers so that a
// change in them cannot make the test agree with a wrong answer.
func TestBcryptPBKDFInto_ReproducesSSHKeygenKeyAndIV(t *testing.T) {
	for _, name := range []string{"ed25519-a16", "ed25519-a1", "ecdsa-a1", "rsa-a1"} {
		t.Run(name, func(t *testing.T) {
			_, raw, _ := fixture(t, name)
			h, err := readOpenSSHHeader(raw)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(h.cipher, []byte("aes256-ctr")) {
				t.Fatalf("fixture cipher is %q, this test decrypts aes256-ctr", h.cipher)
			}
			salt, rounds := kdfOptsOf(t, raw)

			kiv := newTestBuffer(t, opensshKeyIVLen)
			if err := BcryptPBKDFInto([]byte(testPassphrase), salt, int(rounds), kiv); err != nil {
				t.Fatal(err)
			}

			derived := bufferBytes(t, kiv)
			blk, err := aes.NewCipher(derived[:32])
			if err != nil {
				t.Fatal(err)
			}
			plain := make([]byte, len(h.privBlock))
			cipher.NewCTR(blk, derived[32:]).XORKeyStream(plain, h.privBlock)

			if !bytes.Equal(plain[0:4], plain[4:8]) {
				t.Fatalf("check integers differ after decryption (%x vs %x): the derived key and IV are not the ones ssh-keygen used",
					plain[0:4], plain[4:8])
			}
			// A negative control: the same derivation at a different cost
			// must NOT open the file, or the check above would pass on
			// anything.
			other := newTestBuffer(t, opensshKeyIVLen)
			if err := BcryptPBKDFInto([]byte(testPassphrase), salt, int(rounds)+1, other); err != nil {
				t.Fatal(err)
			}
			od := bufferBytes(t, other)
			if bytes.Equal(od, derived) {
				t.Fatal("control failed: rounds+1 derived the same key and IV")
			}
			blk2, err := aes.NewCipher(od[:32])
			if err != nil {
				t.Fatal(err)
			}
			wrong := make([]byte, len(h.privBlock))
			cipher.NewCTR(blk2, od[32:]).XORKeyStream(wrong, h.privBlock)
			if bytes.Equal(wrong[0:4], wrong[4:8]) {
				t.Fatal("control failed: the wrong key also produced matching check integers")
			}
		})
	}
}

// TestBcryptPBKDFInto_SaltSpill covers the one input that makes the
// derivation touch the heap: a salt too long for the workspace's reserve
// (60 bytes of salt plus its 4-byte counter). The result must still be
// deterministic and must differ from the same call one byte shorter.
func TestBcryptPBKDFInto_SaltSpill(t *testing.T) {
	long := bytes.Repeat([]byte{'s'}, 200)
	first := deriveBcrypt(t, []byte("password"), long, 4, 32)
	again := deriveBcrypt(t, []byte("password"), long, 4, 32)
	if !bytes.Equal(first, again) {
		t.Fatal("the spilled-salt path is not deterministic")
	}
	if shorter := deriveBcrypt(t, []byte("password"), long[:199], 4, 32); bytes.Equal(first, shorter) {
		t.Fatal("a one-byte-shorter salt derived the same key")
	}
	if reserve := deriveBcrypt(t, []byte("password"), long[:16], 4, 32); bytes.Equal(first, reserve) {
		t.Fatal("a 16-byte salt derived the same key as the 200-byte one")
	}
}

// TestBcryptPBKDFInto_OutputLengthIsAnInput pins a property of
// bcrypt_pbkdf that is easy to assume wrongly: the output is NOT a stream
// truncated to length. The number of blocks and the interleave both depend
// on the requested length, so a 32-byte derivation is not a prefix of a
// 64-byte one from the same inputs. A caller who needs two keys must ask
// for them in one call and split the result, not derive twice at different
// lengths.
func TestBcryptPBKDFInto_OutputLengthIsAnInput(t *testing.T) {
	short := deriveBcrypt(t, []byte("password"), []byte("salt"), 4, 32)
	long := deriveBcrypt(t, []byte("password"), []byte("salt"), 4, 64)
	if bytes.HasPrefix(long, short) {
		t.Fatal("the 32-byte output is a prefix of the 64-byte one; this test encodes the opposite property and one of them is now wrong")
	}
}

// TestBcryptPBKDFInto_Errors pins the refusals the doc enumerates. The
// input bounds come from the fork's own Check, so their wording is the
// fork's; what this test adds is that every one arrives prefixed, and that
// the buffer states only the wrapper can see — nil, destroyed, sealed —
// are refused too.
func TestBcryptPBKDFInto_Errors(t *testing.T) {
	destroyed := newTestBuffer(t, 32)
	if err := destroyed.Destroy(); err != nil {
		t.Fatal(err)
	}
	sealed := newTestBuffer(t, 32)
	if err := sealed.Seal(); err != nil {
		t.Fatal(err)
	}
	tooLong := newTestBuffer(t, MaxBcryptPBKDFKeyLen+1)
	ok := newTestBuffer(t, 32)

	cases := []struct {
		name           string
		password, salt []byte
		rounds         int
		out            *secmem.SecureBuffer
		want           string
	}{
		{"nil out", []byte("p"), []byte("s"), 8, nil, "nil output buffer"},
		{"destroyed out", []byte("p"), []byte("s"), 8, destroyed, secmem.ErrDestroyed.Error()},
		{"sealed out", []byte("p"), []byte("s"), 8, sealed, secmem.ErrSealed.Error()},
		{"out too large", []byte("p"), []byte("s"), 8, tooLong, "keyLen is too large"},
		{"zero rounds", []byte("p"), []byte("s"), 0, ok, "number of rounds is too small"},
		{"negative rounds", []byte("p"), []byte("s"), -1, ok, "number of rounds is too small"},
		{"empty password", nil, []byte("s"), 8, ok, "empty password"},
		{"empty salt", []byte("p"), nil, 8, ok, "bad salt length"},
		{"salt too long", []byte("p"), make([]byte, 1<<20+1), 8, ok, "bad salt length"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			err := BcryptPBKDFInto(c.password, c.salt, c.rounds, c.out)
			if err == nil {
				t.Fatal("want an error, got nil")
			}
			if !strings.Contains(err.Error(), c.want) {
				t.Errorf("error %q does not mention %q", err, c.want)
			}
			if !strings.HasPrefix(err.Error(), "secmemcrypto: ") {
				t.Errorf("error %q is not prefixed by the package name", err)
			}
		})
	}
}

// TestBcryptPBKDFInto_LeavesOutputIntactOnError requires a rejected call to
// leave out as it found it, so a caller that ignores the error does not
// silently use half a key.
func TestBcryptPBKDFInto_LeavesOutputIntactOnError(t *testing.T) {
	out := newTestBuffer(t, 32)
	if _, err := out.CopyIn(bytes.Repeat([]byte{0xAB}, 32), 0); err != nil {
		t.Fatal(err)
	}
	if err := BcryptPBKDFInto(nil, []byte("salt"), 4, out); err == nil {
		t.Fatal("want an error for an empty password")
	}
	if got := bufferBytes(t, out); !bytes.Equal(got, bytes.Repeat([]byte{0xAB}, 32)) {
		t.Errorf("the output buffer was modified by a rejected call: %x", got)
	}
}

// deriveBcrypt derives n bytes and returns them as a plain slice for the
// test to compare; the buffer is destroyed at cleanup.
func deriveBcrypt(t *testing.T, password, salt []byte, rounds, n int) []byte {
	t.Helper()
	out := newTestBuffer(t, n)
	if err := BcryptPBKDFInto(password, salt, rounds, out); err != nil {
		t.Fatal(err)
	}
	return bufferBytes(t, out)
}
